### ISSUE TITLE
Set up dummy EHLO web page

### ISSUE THREAD

**Issue by kewisch** [thunderbird/thunderbird-website#802]
For https://github.com/thunderbird/thunderbird-android/issues/6327 we'd like to set up a dummy website we can use the host name as part of the EHLO command in SMTP, similar to how FairEmail does it at https://dummy.faircode.eu/

This is to preserve privacy and avoid the local IP behind NAT or proxy appearing in the Received headers.

Please use `ehlo.thunderbird.net` as the hostname if possible, it should be reachable both via ipv4 and ipv6.  

I believe we could make this a redirect to a SUMO page, as for SMTP all that is relevant is that it is resolvable. 

I've filed https://github.com/thunderbird/android-knowledgebase-issues/issues/15 to create a KB article at https://support.mozilla.org/kb/thunderbird-smtp-ehlo

**Comment by kewisch** [comment]
In theory we only need a subdomain that resolves to an IP. The web page is there for people reading the logs or viewing received headers and seeing ehlo.thunderbird.net and visiting that site to understand why.

So we can simply do a redirect and we're good on the website.  I created https://support.mozilla.org/kb/thunderbird-smtp-ehlo/ so you could use that.

**Comment by MelissaAutumn** [comment]
I've setup a cname to thunderbird.net for now. When you get a chance can you confirm that works? Thanks!

**Comment by kewisch** [comment]
I get the Apache Testing 123 page now at https://ehlo.thunderbird.net/

**Comment by MelissaAutumn** [comment]
Ah right, it's not setup to redirect any traffic to thunderbird.net. I've created an issue over at thundernest-ansible to setup the redirect. I'll do that once the article is live. 

Since the dns is pointing to our tb.net server, I think it should be okay since the redirect is at server/application level.

**Comment by janbrasna** [comment]
Resolved in https://github.com/thunderbird/thundernest-ansible/issues/57 and serving:

```yaml
~ $ https -v HEAD ehlo.thunderbird.net 

HEAD / HTTP/1.1
Accept: */*
Host: ehlo.thunderbird.net

HTTP/1.1 302 Found
CF-Cache-Status: HIT
Content-Type: text/html; charset=iso-8859-1
Date: Sat, 17 May 2025 14:17:49 GMT
Expires: Sat, 17 May 2025 14:43:22 GMT
Location: https://support.mozilla.org/kb/thunderbird-smtp-ehlo
```

🚀
