### ISSUE TITLE
Start page redesign

### ISSUE THREAD

**Issue by MelissaAutumn** [thunderbird/thunderbird-website#844]
Via RyanG at Freehive.

![Image](https://github.com/user-attachments/assets/af32ccf2-ff8d-46f3-af22-d8f0e7f730d6)

We can re-use the html created in #840 

#### ESR/Release

```css
background: 
    linear-gradient(to top right, 
    rgba(18, 133, 252, 0.14) 0%,
    rgba(18, 133, 252, 0) 33%,
    rgba(18, 133, 252, 0) 67%,
    rgba(18, 133, 252, 0.14) 100%
    ),
    linear-gradient(to right, 
    rgba(34, 13, 252, 0.05) 0%,
    rgba(34, 13, 252, 0) 30%,
    rgba(34, 13, 252, 0.05) 100%
    );
```

#### Beta

```css
background: 
    linear-gradient(to top right, 
    rgba(18, 131, 252, 0.14) 0%, 
    rgba(18, 131, 252, 0) 33%,  
    rgba(18, 131, 252, 0) 67%,  
    rgba(18, 131, 252, 0.14) 100% 
    ),
    linear-gradient(to right, 
    rgba(12, 244, 252, 0.05) 0%,  
    rgba(12, 244, 252, 0) 30%,   
    rgba(12, 244, 252, 0.05) 100% 
    ); 
```

#### Daily
```css
background:
    linear-gradient(to top right,
    rgba(143, 18, 252, 0.14) 0%,
    rgba(143, 18, 252, 0) 33%,
    rgba(143, 18, 252, 0) 67%,
    rgba(143, 18, 252, 0.14) 100%
    ),
    linear-gradient(to right,
    rgba(32, 12, 252, 0.05) 0%,
    rgba(32, 12, 252, 0) 30%,
    rgba(32, 12, 252, 0.05) 100%
    ); 
```

**Comment by ryangorley** [comment]
@MelissaAutumn I don't know how you want to build the gradients on these. I kind of like having the container for the buttons have a radial gradient, rather than each button. If you want to build it that way, here is how I would style that container:

```css
.button-set-container {
    display: flex;
    flex-direction: row;
    flex-wrap: wrap;
    gap: 1rem;
    justify-content: center;
    align-items: center;
    position: relative;
    padding: 2rem 4rem;
}

.button-set-container::before {
    content: "";
    position: absolute;
    top: 0;
    left: 0;
    width: 100%;
    height: 100%;
    background: radial-gradient(ellipse at center, rgba(58, 42, 252, 0.25) 0%, transparent 70%);
    pointer-events: none;
    z-index: 0;
}
```

Here are the background values for each:

ESR/Release: `background: radial-gradient(ellipse at center, rgba(58, 42, 252, 0.25) 0%, transparent 70%);`

Beta: `background: radial-gradient(ellipse at center, rgba(42, 143, 252, 0.25) 0%, transparent 70%);`

Daily: `background: radial-gradient(ellipse at center, rgba(154, 42, 252, 0.25) 0%, transparent 70%);`
